# Default values for imageUploadChart.
# This is a YAML-formatted file.

# image:
#   repository: empower9090/image-upload-logic
#   tag: latest

global:
  imageUploadImage: empower9090/image-upload-logic:latest

labels:
  app: image-upload-pod