apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: concrete-gallery-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: concrete-gallery-cert
    kubernetes.io/ingress.global-static-ip-name: "concrete-detection-ip"
spec:
  ingressClassName: gce 
  rules:
    - host: mahesh.concretecrackgallery.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: concrete-image-gallery-svc-lb
                port:
                  number: 8082
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: image-upload-svc-lb
                port:
                  number: 8080
          - path: /uploaded
            pathType: Prefix
            backend:
              service:
                name: image-upload-svc-lb
                port:
                  number: 8080
