apiVersion: v1
kind: Service
metadata:
  name: concrete-image-gallery-svc-lb
spec:
  selector:
    app: concrete-image-gallery-pod
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
