apiVersion: v1
kind: Service
metadata:
  name: crack-detection-svc
spec:
  selector:
    app: crack-detection-pod
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  # type: LoadBalancer
