name: GCP Bootstrap Infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform-bootstrap:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/gcp-bootstrap

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Apply)
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform plan -input=false

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Terraform Plan (Destroy with targets)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform plan -destroy -input=false \
            -target=google_service_account.crack_detection_sa \
            -target=google_project_iam_member.sa_roles \
            -target=google_dns_managed_zone.crack_dns \
            -target=google_dns_record_set.root_a_record \
            -target=google_dns_record_set.www_a_record

      - name: Terraform Destroy (with targets)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform destroy -auto-approve \
            -target=google_service_account.crack_detection_sa \
            -target=google_project_iam_member.sa_roles \
            -target=google_dns_managed_zone.crack_dns \
            -target=google_dns_record_set.root_a_record \
            -target=google_dns_record_set.www_a_record
