name: Mahesh Build and push docker images

on:
  push:
    branches:
      - master
      - slownessFix
  workflow_dispatch: # Enables manual trigger from the GitHub Actions tab
    inputs:
      image_tag:
        description: 'Docker image tag to push'
        required: true
        default: 'latest'
        type: string
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.MAHESH_DOCKER_USERNAME }}
        password: ${{ secrets.MAHESH_DOCKER_PASSWORD }}

    - name: Build and Push Image Upload Logic
      run: |
        cd buildConcreteDetection/imageUpload
        docker build -f dockerfile -t ${{ secrets.MAHESH_DOCKER_USERNAME }}/image-upload-logic:${{ github.event.inputs.image_tag || 'latest' }} .
        docker push ${{ secrets.MAHESH_DOCKER_USERNAME }}/image-upload-logic:${{ github.event.inputs.image_tag || 'latest' }}

    - name: Build and Push Crack Detection Logic
      run: |
        cd buildConcreteDetection/crackDetection
        docker build -f dockerfile -t ${{ secrets.MAHESH_DOCKER_USERNAME }}/crack-detection-logic:${{ github.event.inputs.image_tag || 'latest' }} .
        docker push ${{ secrets.MAHESH_DOCKER_USERNAME }}/crack-detection-logic:${{ github.event.inputs.image_tag || 'latest' }}

    - name: Build and Push Concrete Image Gallery Logic
      run: |
        cd buildConcreteDetection/concreteImageGallery
        docker build -f dockerfile -t ${{ secrets.MAHESH_DOCKER_USERNAME }}/concrete-image-gallery-logic:${{ github.event.inputs.image_tag || 'latest' }} .
        docker push ${{ secrets.MAHESH_DOCKER_USERNAME }}/concrete-image-gallery-logic:${{ github.event.inputs.image_tag || 'latest' }}
